interface RGB
{
    void RGB();
    void RGB([ ToWASMOwned, Value ] octet r, [ ToWASMOwned, Value ] octet g, [ ToWASMOwned, Value ] octet b);
    attribute octet r;
    attribute octet g;
    attribute octet b;
};
